name: ewselect
favicon: null
layout_spectrum: 0.33185887592844665
typography_spectrum: 0.9003194833640009
title: EW Select Travel Concierge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1110'
    - '#f9fafa'
    - '#644e3f'
    - '#fdb59f'
    - '#7eb0b7'
  brandStrength: 0.875
  lightness: 0.7941542463377118
  saturation: 0.5369295594282448
  rhythmicContrast: 0.47514578932896256
purpose: []
