name: ewselect
favicon: null
layout_spectrum: 0.33185887592844665
typography_spectrum: 0.9003194833640009
title: EW Select Travel Concierge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfa'
    - '#60b1e8'
    - '#060d06'
    - '#546113'
    - '#91912a'
  brandStrength: 1
  lightness: 0.7941542463377118
  saturation: 1
  rhythmicContrast: 0.47514578932896256
purpose: []
